<?php
/**
 * UserAddRequestNewPermissionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BioTrack API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserAddRequestNewPermissionsTest Class Doc Comment
 *
 * @category    Class
 * @description UserAddRequestNewPermissions
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserAddRequestNewPermissionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserAddRequestNewPermissions"
     */
    public function testUserAddRequestNewPermissions()
    {
    }

    /**
     * Test attribute "inventory_convert"
     */
    public function testPropertyInventoryConvert()
    {
    }

    /**
     * Test attribute "sale_dispense"
     */
    public function testPropertySaleDispense()
    {
    }

    /**
     * Test attribute "sale_modify"
     */
    public function testPropertySaleModify()
    {
    }

    /**
     * Test attribute "sale_void"
     */
    public function testPropertySaleVoid()
    {
    }

    /**
     * Test attribute "sale_refund"
     */
    public function testPropertySaleRefund()
    {
    }

    /**
     * Test attribute "justauthenticate"
     */
    public function testPropertyJustauthenticate()
    {
    }

    /**
     * Test attribute "employee_add"
     */
    public function testPropertyEmployeeAdd()
    {
    }

    /**
     * Test attribute "employee_modify"
     */
    public function testPropertyEmployeeModify()
    {
    }

    /**
     * Test attribute "employee_remove"
     */
    public function testPropertyEmployeeRemove()
    {
    }

    /**
     * Test attribute "vehicle_add"
     */
    public function testPropertyVehicleAdd()
    {
    }

    /**
     * Test attribute "vehicle_modify"
     */
    public function testPropertyVehicleModify()
    {
    }

    /**
     * Test attribute "vehicle_remove"
     */
    public function testPropertyVehicleRemove()
    {
    }

    /**
     * Test attribute "plant_room_add"
     */
    public function testPropertyPlantRoomAdd()
    {
    }

    /**
     * Test attribute "plant_room_modify"
     */
    public function testPropertyPlantRoomModify()
    {
    }

    /**
     * Test attribute "plant_room_remove"
     */
    public function testPropertyPlantRoomRemove()
    {
    }

    /**
     * Test attribute "inventory_room_add"
     */
    public function testPropertyInventoryRoomAdd()
    {
    }

    /**
     * Test attribute "inventory_room_modify"
     */
    public function testPropertyInventoryRoomModify()
    {
    }

    /**
     * Test attribute "inventory_room_remove"
     */
    public function testPropertyInventoryRoomRemove()
    {
    }

    /**
     * Test attribute "plant_destroy_schedule"
     */
    public function testPropertyPlantDestroySchedule()
    {
    }

    /**
     * Test attribute "plant_destroy_schedule_undo"
     */
    public function testPropertyPlantDestroyScheduleUndo()
    {
    }

    /**
     * Test attribute "plant_destroy"
     */
    public function testPropertyPlantDestroy()
    {
    }

    /**
     * Test attribute "plant_harvest_schedule"
     */
    public function testPropertyPlantHarvestSchedule()
    {
    }

    /**
     * Test attribute "plant_harvest_schedule_undo"
     */
    public function testPropertyPlantHarvestScheduleUndo()
    {
    }

    /**
     * Test attribute "plant_harvest"
     */
    public function testPropertyPlantHarvest()
    {
    }

    /**
     * Test attribute "plant_new"
     */
    public function testPropertyPlantNew()
    {
    }

    /**
     * Test attribute "plant_new_undo"
     */
    public function testPropertyPlantNewUndo()
    {
    }

    /**
     * Test attribute "plant_convert_to_inventory"
     */
    public function testPropertyPlantConvertToInventory()
    {
    }

    /**
     * Test attribute "plant_cure"
     */
    public function testPropertyPlantCure()
    {
    }

    /**
     * Test attribute "plant_yield_modify"
     */
    public function testPropertyPlantYieldModify()
    {
    }

    /**
     * Test attribute "plant_waste_weigh"
     */
    public function testPropertyPlantWasteWeigh()
    {
    }

    /**
     * Test attribute "inventory_new"
     */
    public function testPropertyInventoryNew()
    {
    }

    /**
     * Test attribute "inventory_manifest_lookup"
     */
    public function testPropertyInventoryManifestLookup()
    {
    }

    /**
     * Test attribute "inventory_transfer_inbound"
     */
    public function testPropertyInventoryTransferInbound()
    {
    }

    /**
     * Test attribute "inventory_transfer_inbound_modify"
     */
    public function testPropertyInventoryTransferInboundModify()
    {
    }

    /**
     * Test attribute "inventory_transfer_lookup"
     */
    public function testPropertyInventoryTransferLookup()
    {
    }

    /**
     * Test attribute "inventory_transfer_outbound"
     */
    public function testPropertyInventoryTransferOutbound()
    {
    }

    /**
     * Test attribute "inventory_transfer_outbound_modify"
     */
    public function testPropertyInventoryTransferOutboundModify()
    {
    }

    /**
     * Test attribute "inventory_transfer_outbound_void"
     */
    public function testPropertyInventoryTransferOutboundVoid()
    {
    }

    /**
     * Test attribute "plant_move"
     */
    public function testPropertyPlantMove()
    {
    }

    /**
     * Test attribute "plant_modify"
     */
    public function testPropertyPlantModify()
    {
    }

    /**
     * Test attribute "inventory_adjust"
     */
    public function testPropertyInventoryAdjust()
    {
    }

    /**
     * Test attribute "inventory_adjust_usable"
     */
    public function testPropertyInventoryAdjustUsable()
    {
    }

    /**
     * Test attribute "inventory_sample"
     */
    public function testPropertyInventorySample()
    {
    }

    /**
     * Test attribute "inventory_qa_check"
     */
    public function testPropertyInventoryQaCheck()
    {
    }

    /**
     * Test attribute "inventory_qa_check_all"
     */
    public function testPropertyInventoryQaCheckAll()
    {
    }

    /**
     * Test attribute "inventory_qa_sample"
     */
    public function testPropertyInventoryQaSample()
    {
    }

    /**
     * Test attribute "inventory_qa_sample_void"
     */
    public function testPropertyInventoryQaSampleVoid()
    {
    }

    /**
     * Test attribute "inventory_qa_sample_results"
     */
    public function testPropertyInventoryQaSampleResults()
    {
    }

    /**
     * Test attribute "inventory_manifest_pickup"
     */
    public function testPropertyInventoryManifestPickup()
    {
    }

    /**
     * Test attribute "inventory_manifest_modify"
     */
    public function testPropertyInventoryManifestModify()
    {
    }

    /**
     * Test attribute "inventory_manifest"
     */
    public function testPropertyInventoryManifest()
    {
    }

    /**
     * Test attribute "inventory_manifest_void"
     */
    public function testPropertyInventoryManifestVoid()
    {
    }

    /**
     * Test attribute "inventory_manifest_void_stop"
     */
    public function testPropertyInventoryManifestVoidStop()
    {
    }

    /**
     * Test attribute "inventory_manifest_void_items"
     */
    public function testPropertyInventoryManifestVoidItems()
    {
    }

    /**
     * Test attribute "inventory_create_lot"
     */
    public function testPropertyInventoryCreateLot()
    {
    }

    /**
     * Test attribute "inventory_split"
     */
    public function testPropertyInventorySplit()
    {
    }

    /**
     * Test attribute "user_add"
     */
    public function testPropertyUserAdd()
    {
    }

    /**
     * Test attribute "user_modify"
     */
    public function testPropertyUserModify()
    {
    }

    /**
     * Test attribute "user_remove"
     */
    public function testPropertyUserRemove()
    {
    }

    /**
     * Test attribute "inventory_move"
     */
    public function testPropertyInventoryMove()
    {
    }

    /**
     * Test attribute "inventory_destroy_schedule"
     */
    public function testPropertyInventoryDestroySchedule()
    {
    }

    /**
     * Test attribute "inventory_destroy_schedule_undo"
     */
    public function testPropertyInventoryDestroyScheduleUndo()
    {
    }

    /**
     * Test attribute "inventory_destroy"
     */
    public function testPropertyInventoryDestroy()
    {
    }

    /**
     * Test attribute "tax_obligation_file"
     */
    public function testPropertyTaxObligationFile()
    {
    }

    /**
     * Test attribute "nonce_replay"
     */
    public function testPropertyNonceReplay()
    {
    }

    /**
     * Test attribute "sync_vehicle"
     */
    public function testPropertySyncVehicle()
    {
    }

    /**
     * Test attribute "sync_employee"
     */
    public function testPropertySyncEmployee()
    {
    }

    /**
     * Test attribute "sync_plant_room"
     */
    public function testPropertySyncPlantRoom()
    {
    }

    /**
     * Test attribute "sync_inventory_room"
     */
    public function testPropertySyncInventoryRoom()
    {
    }

    /**
     * Test attribute "sync_inventory"
     */
    public function testPropertySyncInventory()
    {
    }

    /**
     * Test attribute "sync_plant"
     */
    public function testPropertySyncPlant()
    {
    }

    /**
     * Test attribute "sync_plant_derivative"
     */
    public function testPropertySyncPlantDerivative()
    {
    }

    /**
     * Test attribute "sync_manifest"
     */
    public function testPropertySyncManifest()
    {
    }

    /**
     * Test attribute "sync_inventory_transfer"
     */
    public function testPropertySyncInventoryTransfer()
    {
    }

    /**
     * Test attribute "sync_inventory_transfer_inbound"
     */
    public function testPropertySyncInventoryTransferInbound()
    {
    }

    /**
     * Test attribute "sync_sale"
     */
    public function testPropertySyncSale()
    {
    }

    /**
     * Test attribute "sync_tax_report"
     */
    public function testPropertySyncTaxReport()
    {
    }

    /**
     * Test attribute "sync_vendor"
     */
    public function testPropertySyncVendor()
    {
    }

    /**
     * Test attribute "sync_qa_lab"
     */
    public function testPropertySyncQaLab()
    {
    }

    /**
     * Test attribute "sync_check"
     */
    public function testPropertySyncCheck()
    {
    }

    /**
     * Test attribute "sync_inventory_adjust"
     */
    public function testPropertySyncInventoryAdjust()
    {
    }

    /**
     * Test attribute "sync_inventory_qa_sample"
     */
    public function testPropertySyncInventoryQaSample()
    {
    }

    /**
     * Test attribute "sync_inventory_sample"
     */
    public function testPropertySyncInventorySample()
    {
    }

    /**
     * Test attribute "inventory_transfer_outbound_return_lookup"
     */
    public function testPropertyInventoryTransferOutboundReturnLookup()
    {
    }

    /**
     * Test attribute "inventory_transfer_outbound_return"
     */
    public function testPropertyInventoryTransferOutboundReturn()
    {
    }

    /**
     * Test attribute "inventory_convert_undo"
     */
    public function testPropertyInventoryConvertUndo()
    {
    }

    /**
     * Test attribute "card_lookup"
     */
    public function testPropertyCardLookup()
    {
    }
}
